package firebird

import (
	"strings"

	"github.com/toudi/gorpheus/v2/internal/ddl/column"
)

func (fd *fbDialect) integerDDL(c *column.Column, buffer *strings.Builder) error {
	if c.Type == column.TypeSmallInt {
		buffer.WriteString("SMALLINT")
	} else if c.Type == column.TypeInt {
		buffer.WriteString("INTEGER")
	} else if c.Type == column.TypeBigInt {
		buffer.WriteString("BIGINT")
	} else if c.Type == column.TypeInt128 {
		buffer.WriteString("INT128")
	}

	if c.AutoIncrement != nil && *c.AutoIncrement {
		buffer.WriteString(" GENERATED BY DEFAULT AS IDENTITY")
	}
	return nil
}
