on:
  push:
    # run only against tags
    tags:
      - "*"
    branches:
      - "**"

permissions:
  contents: write

jobs:
  test:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - run: go test ./...

  build-documentation:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tonynv/asciidoctor-action@master
        with:
          program: |
            asciidoctor-pdf \
            -o docs/gorpheus.pdf \
            -a toc \
            -a source-highlighter=rouge \
            docs/index.adoc
      - uses: actions/upload-artifact@v4
        with:
          name: gorpheus.pdf
          path: docs/gorpheus.pdf

  build:
    needs: [test]
    name: build binaries
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, macos-13]
        tags: [all, firebird, sqlite3, postgresql]
        include:
          - runner: ubuntu-latest
            os: linux
            arch: amd64
          - runner: macos-latest
            os: darwin
            arch: arm64
          - runner: macos-13
            os: darwin
            arch: amd64

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Override arm64 -> m1
        run: |
          ARCH=$(echo ${{ matrix.arch }} | sed 's/arm64/m1/')
          echo "ARCH=$ARCH" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - run: mkdir dist
      - run: go mod tidy
        working-directory: cmd/gorpheus

      - env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        working-directory: cmd/gorpheus
        run: |
          go build -tags=${{ matrix.tags }} \
          -o ../../gorpheus-${{ matrix.tags }}.${{ matrix.os }}.${{ env.ARCH }}

      - uses: actions/upload-artifact@v4
        with:
          name: gorpheus-${{ matrix.tags }}.${{ matrix.os }}.${{ env.ARCH }}
          path: gorpheus-${{ matrix.tags }}.${{ matrix.os }}.${{ env.ARCH }}

  release:
    needs: [build, build-documentation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: gorpheus*
          path: assets
          merge-multiple: true

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: assets/gorpheus*
